# get api_id & api_hash from my.telegram.org
api_id: 27264334
api_hash: '0d48bec55aca309215ad69cb844868e5'
# 13 digit channel id startswith - like -111.......
dump_id: -1001841775749
# genrate session of ur tg ac for telethon run sessionmaker.py
string_session: '1BJWap1sBuy4T9bwglAswLeOxXfBTRD7QpWGtMEcPpIVqegIBvxB7T7kR9OFCLzNxj1vg7LdvACZZy-2ScQJEn6tc4eSTSxUSMsVWtkjVvAJvU5NPoXl_fpKsghlALGtwI-SifX-jfoFkeRZaPdiseQiX0QDjnyfC2SHM5cBFd69XsOf8tkElMoJSgrPb6iJ9ExgJTIJalJB-NdzPAPjbqyu2d9exXXJaoQA0mrxZgYzwvxLxewcld2GOh5qeHzFJmzeAcELDb-rG8wvDK2joNRjGg88eBYL8XGHAafFE47_Iq3zwepOcUtc1anCKYXTSaSkZ2EBe3FHKPfT0tfIxx6mDIQzNQqY='
